version: "3.7"
services:
    node:
        build:
            context: .
            dockerfile: dev.Dockerfile
        environment: 
            NODE_ENV: development
            PORT: 7001
        ports:
            - 7001:7001
        container_name: node
        volumes:
            - ./:/app
            - nodemodules:/app/node_modules
volumes:
    nodemodules: {}
